version: 2
project_name: credly-badges
release:
  github:
    owner: mikejoh
    name: credly-badges
  name_template: "v{{ .Tag }}"
builds:
  - id: credly-badges
    targets:
      - linux_amd64_v1
      - darwin_amd64_v1
      - windows_amd64_v1
    dir: .
    main: ./cmd/credly-badges/
    binary: credly-badges
    builder: go
    gobinary: go
    command: build
dist: ./build
