name: "Credly Badges"
description: "Add Credly badges to your README."
author: "mikejoh"

inputs:
  CREDLY_USERNAME:
    description: "Credly username"
    default: ${{ github.actor }}
    required: false

runs:
  using: "docker"
  image: "Dockerfile"

branding:
  icon: "award"
  color: "green"
